
services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    expose: 
      - 3306
    env_file:
      - .env
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - net

  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    expose: 
      - 9000
    volumes:
      - wordpress:/var/www
    env_file:
      - .env
    networks:
      - net

  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    depends_on: 
      - wordpress
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www
    restart: always
    networks:
      - net

volumes: 
  wordpress:
    driver: local
    driver_opts:
      device: /home/rennatiq/data/wordpress
      type: "none"
      o: bind

  mariadb:
    driver: local
    driver_opts:
      device: /home/rennatiq/data/mariadb
      type: "none"
      o: bind

networks:
  net: