
services: 

  mariadb:
    # image: mariadb:10
    container_name: mariadb
    build: 
      context: .
      dockerfile: /home/rennatiq/project/srcs/requirements/mariadb/Dockerfile
    expose: 
      - 3306
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    restart: always
    volumes:
      -mariadb:/var/www
    networks:
      - net
  wordpress:
    # image: wordpress:5-fpm-alpine
    container_name: wordpress
    build: 
      context: .
      dockerfile: /home/rennatiq/project/srcs/requirements/wordpress/Dockerfile
    links:
      - mariadb
    volumes:
      - wordpress:/var/www
    environment:
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
    networks:
      - net
  nginx:
    container_name: nginx
    build: 
      context: .
      dockerfile: /home/rennatiq/project/srcs/requirements/nginx/Dockerfile
    depends_on: 
      - wordpress
    ports:
      - 8080:8080
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - wordpress:/var/www
    restart: always
    networks:
      - net

volumes: 
  wordpress:
    driver_opts:
      device: /home/rennatiq/data/wordpress
      type: "none"
      o: bind

  mariadb:
    driver_opts:
      device: /home/rennatiq/data/database
      type: "none"
      o: bind

networks:
  net: