
services: 

  mariadb:
    container_name: mariadb
    image: mariadb:42
    build: 
      context: .
      dockerfile: /home/rennatiq/project/srcs/requirements/mariadb/Dockerfile
    expose: 
      - 3306
    env_file:
      - .env
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - net
  wordpress:
    container_name: wordpress
    image: wordpress:42
    build: 
      context: .
      dockerfile: /home/rennatiq/project/srcs/requirements/wordpress/Dockerfile
    depends_on:
      - mariadb
    expose: 
      - 9000
    volumes:
      - wordpress:/var/www
    env_file:
      - .env

    networks:
      - net
  nginx:
    container_name: nginx
    image: nginx:42
    build: 
      context: .
      dockerfile: /home/rennatiq/project/srcs/requirements/nginx/Dockerfile
    depends_on: 
      - wordpress
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www
    restart: always
    networks:
      - net

volumes: 
  wordpress:
    driver: local
    driver_opts:
      device: /home/rennatiq/data/wordpress
      type: "none"
      o: bind

  mariadb:
    driver: local
    driver_opts:
      device: /home/rennatiq/data/mariadb
      type: "none"
      o: bind

networks:
  net: